### ISSUE TITLE
Compile Delphi CommunityEdition 10.4 never-build package 'designide' must be recompiled

### ISSUE THREAD

**Issue by destroyerstv** [Virtual-TreeView/Virtual-TreeView#1068]
Install 
VirtualTreesD.dpk 
Show error:
never-build package 'designide' must be recompiled

**Comment by joachimmarder** [comment]
Cannot reproduce. Is this 10.4 with all updates (aka 10.4.2)?
Which version of Virtual TreeView are you using? V7.6.1 official release? Or master branch?

**Comment by joachimmarder** [comment]
Similar problem here: https://github.com/SynEdit/SynEdit/issues/167

**Comment by destroyerstv** [comment]
I have Delphi Community Edition last version from official site Embarcadero.
VirtualTreeView download last version from https://customers.jam-software.de/downloadTrial.php?language=EN&article_no=407

**Comment by destroyerstv** [comment]
The problem is solved as follows:
1. Open VirtualTreeView.groupproj
2. VirtualTreesR*.bpl (My VirtualTreesR270.bpl) -> Project -> Options -> Description
3. Set Usage options Designtime and runtime, set Build control Rebuild as needed and click [Save]
4. Build VirtualTreesR*.bpl and Install 
5. Build VirtualTreesD*.bpl and Install
If you have error not find VirtualTreesR.dcp. Check: Tools -> Options -> Language -> Delphi -> Library -> DCP output directory
and Add in project VirtualTreesR.dcp

"Stay strong! The weak are always unlucky"

**Comment by joachimmarder** [comment]
So the solution is to configure the runtime package as designtime + runtime package?!
Seems like a bug in the community edition to me.
